### ISSUE TITLE
Check Ring et al. 2019 for further relevant datasets

### ISSUE THREAD

**Issue by ru37z** [fkie-cad/intrusion-detection-datasets#22]
Did you already check this paper? (thanks to Maxime for the hint!)

Markus Ring, Sarah Wunderlich, Deniz Scheuring, Dieter Landes, Andreas Hotho: "A survey of network-based intrusion detection data sets", Computers & Security, 2019.

https://www.sciencedirect.com/science/article/pii/S016740481930118X

**Comment by Maspital** [comment]
This survey is covered (here)[https://fkie-cad.github.io/intrusion-detection-datasets/content/related_work/#a-survey-of-network-based-intrusion-detection-data-sets-2019].

I found it to be the most comprehensive survey of all the ones I looked at, it's also one of the few providing more than just a basic description of each dataset. Covers only network-based datasets, though.
